import type { Metadata } from 'next';
import { NavBar } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BookLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-[calc(100vh-6rem)]">{children}</div>
      <NavBar mode={'CHILD'} />
    </>
  );
}
