import type { Metadata } from 'next';
import { MSWComponent } from './_component/MSWComponent';
import AuthContext from '@/context/AuthContext';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-custom-black-with-opacity">
        <AuthContext>
          <MSWComponent />
          <div className="w-[36rem] min-h-[64rem] mx-auto bg-custom-white">
            {children}
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
