import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoanApplyLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  console.log(modal);
  return (
    <>
      <div className="pb-[3rem]">
        {children}
        {modal}
      </div>
    </>
  );
}
